### PR TITLE
Update to 1.17 and java 16

### PR DESCRIPTION
**Pull request by MicherGit**
updated to 21w19a

### CODE REVIEW

**Comment by MicherGit** [comment]
im going to test by publishing this to a private maven to see if it works

**Comment by MicherGit** [comment]
Should work now.

**Comment by kyrptonaught** [comment]
Everything is working as is?

**Comment by MicherGit** [comment]
after some testing it appears something broke it, idk what happened but i will try to figure out why it keeps crashing on me

**Comment by MicherGit** [comment]
aight everything should be fine / ready for release except for the maven part

**Comment by kyrptonaught** [comment]
Good work! Thank you! I'm gonna merge this then just verify it's inline with the last 1.16 branch. I may have some unpushed local changes hanging around too

**Comment by kyrptonaught** [comment]
Seems to be working good! Thanks again. I did remove the acesswidener, as there are getters available for yaw and pitch

**Comment by MicherGit** [comment]
I ported it based off the 1.17 branch, and thank you too :D

**Pull request merged**
